### ISSUE TITLE
Docker Mac CE external storage error

### ISSUE THREAD

**Issue by impactcolor** [wattry/run-docker-external-storage#1]
Thanks for documenting this.  I have a problem with the final check:

When I run this command:
`diff --brief -r $EHOME/Library/Containers/com.docker.docker $HOME/Library/Containers/com.docker.docker`

Only in /Volumes/KESU/Users/ohms/Library/Containers/com.docker.docker: ._com.docker.docker
Only in /Users/ohms/Library/Containers/com.docker.docker/Data: backend.sock
Only in /Users/ohms/Library/Containers/com.docker.docker/Data: docker.sock
Only in /Users/ohms/Library/Containers/com.docker.docker/Data: osxfs.sock
Only in /Users/ohms/Library/Containers/com.docker.docker/Data/vms/0: 00000002.000005f4
Only in /Users/ohms/Library/Containers/com.docker.docker/Data/vms/0: 00000002.00001000
Only in /Users/ohms/Library/Containers/com.docker.docker/Data/vms/0: 00000002.00001001
Only in /Users/ohms/Library/Containers/com.docker.docker/Data/vms/0: 00000002.0000f3a5
Only in /Users/ohms/Library/Containers/com.docker.docker/Data/vms/0: 00000003.000005f5
Only in /Users/ohms/Library/Containers/com.docker.docker/Data/vms/0: 00000003.00000948

I ran rsync.  Then I ran mv and same thing.
Any ideas?

**Comment by wattry** [comment]
@impactcolor I hope you figured this out because I honestly just saw this today. I'm sorry for not getting back to you.

if you ever see this, my first thoughts would be a permission issue.  Mac treats the Library folder differently. If you run the rsync or move function in sudo it may solve your problem.

**Comment by 09wattry** [comment]
@impactcolor if you ever see this, my first thoughts would be a permission issue.  Mac treats the Library folder differently. If you run the rsync or move function in sudo it may solve your problem.

**Comment by wattry** [comment]
I'm going to close this in a week unless there is more feedback
