### ISSUE TITLE
In Big Sur have a problem

### ISSUE THREAD

**Issue by TianYa-Q** [wattry/run-docker-external-storage#6]
need only symbolic link /vms/0/data. If link all files will have troubles.

**Comment by doza62** [comment]
You are a savior!

**Comment by jcuero** [comment]
Thanks! your answer helped me. `macOS Big Sur 11.2.3 (20D91)`

Be careful if you copy and paste because sometimes you copy an invalid character -after a couple of hours I realized :( -

```
export E=/Volumes/<external-name>
export EHOME=$E$HOME
export EHOME_EXTERNAL="$EHOME/Library/Containers/com.docker.docker/Data/vms/0/data"

ln -sfn $EHOME_EXTERNAL ~/Library/Containers/com.docker.docker/Data/vms/0/data
```

**Comment by bskiefer** [comment]
Still creates the default qcow2 file instead of using Docker.raw :/

**Comment by TianYa-Q** [comment]
> Still creates the default qcow2 file instead of using Docker.raw :/

You don't need to do it any more. Just change the location in preferences -> advanced -> disk image location.
This option is in the end of the list.
